# ----------------------------------------------
# title: docker-compose.yml
# author: Robin Marques
# date: 2026-01-07
# updated: 2026-01-07
# type: configuration
# status: active
# tags:
#   - docker
#
# description: Fichier de configuration Docker Compose pour déployer les services nécessaires à la gestion des ruches connectées.
# ----------------------------------------------

services:
  # ========== Services Docker Compose ==========
  #
  # Service de base de données PostgreSQL pour stocker les données des ruches.
  #
  # ============================================
  database:
    image: postgres:15
    container_name: hive_db
    environment:
      POSTGRES_DB: ruche_db
      POSTGRES_USER: apiculteur
      POSTGRES_PASSWORD: password_pfe
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U apiculteur -d ruche_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # ========= MQTT Broker Service ==========
  #
  # Service MQTT Broker utilisant Eclipse Mosquitto. 
  # Il gère la communication entre les capteurs des ruches et le backend.
  #
  # ========================================
  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: hive_mqtt_broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: always

  # ========= Backend API Service ==========
  #
  # Service backend API développé en Python avec Flask. Il traite les données reçues des capteurs et fournit une API RESTful.
  #
  # ========================================
  api_backend:
    build: 
      context: ../backend
      dockerfile: Dockerfile
    container_name: hive_api_backend
    ports:
      - "5000:5000"
    depends_on:
      mqtt-broker:
        condition: service_started
      database:
          condition: service_healthy
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  postgres_data: